-- Seed the requested YouTube audiobook catalog entries.
-- Safe to apply more than once; all rows are keyed by the canonical YouTube URL.

INSERT OR IGNORE INTO intake_items (id, telegram_update_id, telegram_file_id, media_type, source_type, source_url, source_chat_id, source_message_id, status, original_filename, mime_type, created_at, updated_at) VALUES ('youtube-seed-01', -900001, 'youtube:gtSUuYbtRpQ', 'document', 'youtube_link', 'https://www.youtube.com/watch?v=gtSUuYbtRpQ', 'seed', 1, 'published', 'ဂျူး - အမှတ်တရ (စ-ဆုံး)', 'text/uri-list', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO rights_records (id, intake_id, rights_status, evidence_note, created_at, updated_at) VALUES ('youtube-rights-01', 'youtube-seed-01', 'missing', 'YouTube link seed; verify rights before relying on continued availability.', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO book_drafts (id, intake_id, title, slug, author, category, summary, youtube_url, metadata_json, publication_status, created_at, updated_at) VALUES ('youtube-book-01', 'youtube-seed-01', 'ဂျူး - အမှတ်တရ (စ-ဆုံး)', 'youtube-gtsuuybtrpq', 'ဂျူး', 'အသံစာအုပ်', 'YouTube မှ နားဆင်နိုင်သော အသံဇာတ်လမ်း။', 'https://www.youtube.com/watch?v=gtSUuYbtRpQ', '{"source":"seed","sourceType":"youtube","public":{"sourceType":"youtube"}}', 'published', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');

INSERT OR IGNORE INTO intake_items (id, telegram_update_id, telegram_file_id, media_type, source_type, source_url, source_chat_id, source_message_id, status, original_filename, mime_type, created_at, updated_at) VALUES ('youtube-seed-02', -900002, 'youtube:XlOGj4hRzP0', 'document', 'youtube_link', 'https://www.youtube.com/watch?v=XlOGj4hRzP0', 'seed', 2, 'published', 'ဂျူး - မလျှောက်ဖြစ်သောလမ်း (စ-ဆုံး)', 'text/uri-list', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO rights_records (id, intake_id, rights_status, evidence_note, created_at, updated_at) VALUES ('youtube-rights-02', 'youtube-seed-02', 'missing', 'YouTube link seed; verify rights before relying on continued availability.', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO book_drafts (id, intake_id, title, slug, author, category, summary, youtube_url, metadata_json, publication_status, created_at, updated_at) VALUES ('youtube-book-02', 'youtube-seed-02', 'ဂျူး - မလျှောက်ဖြစ်သောလမ်း (စ-ဆုံး)', 'youtube-xlogj4hrzp0', 'ဂျူး', 'အသံစာအုပ်', 'YouTube မှ နားဆင်နိုင်သော အသံဇာတ်လမ်း။', 'https://www.youtube.com/watch?v=XlOGj4hRzP0', '{"source":"seed","sourceType":"youtube","public":{"sourceType":"youtube"}}', 'published', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');

INSERT OR IGNORE INTO intake_items (id, telegram_update_id, telegram_file_id, media_type, source_type, source_url, source_chat_id, source_message_id, status, original_filename, mime_type, created_at, updated_at) VALUES ('youtube-seed-03', -900003, 'youtube:AjKVqr71qOs', 'document', 'youtube_link', 'https://www.youtube.com/watch?v=AjKVqr71qOs', 'seed', 3, 'published', 'ပုညခင် - လက်ကျန်လရောင် (စ-ဆုံး)', 'text/uri-list', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO rights_records (id, intake_id, rights_status, evidence_note, created_at, updated_at) VALUES ('youtube-rights-03', 'youtube-seed-03', 'missing', 'YouTube link seed; verify rights before relying on continued availability.', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO book_drafts (id, intake_id, title, slug, author, category, summary, youtube_url, metadata_json, publication_status, created_at, updated_at) VALUES ('youtube-book-03', 'youtube-seed-03', 'ပုညခင် - လက်ကျန်လရောင် (စ-ဆုံး)', 'youtube-ajkvqr71qos', 'ပုညခင်', 'အသံစာအုပ်', 'YouTube မှ နားဆင်နိုင်သော အသံဇာတ်လမ်း။', 'https://www.youtube.com/watch?v=AjKVqr71qOs', '{"source":"seed","sourceType":"youtube","public":{"sourceType":"youtube"}}', 'published', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');

INSERT OR IGNORE INTO intake_items (id, telegram_update_id, telegram_file_id, media_type, source_type, source_url, source_chat_id, source_message_id, status, original_filename, mime_type, created_at, updated_at) VALUES ('youtube-seed-04', -900004, 'youtube:voz5DL2ZKW0', 'document', 'youtube_link', 'https://www.youtube.com/watch?v=voz5DL2ZKW0', 'seed', 4, 'published', 'ခင်ခင်ထူး - မအိမ်ကံ (စ-ဆုံး ၁)', 'text/uri-list', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO rights_records (id, intake_id, rights_status, evidence_note, created_at, updated_at) VALUES ('youtube-rights-04', 'youtube-seed-04', 'missing', 'YouTube link seed; verify rights before relying on continued availability.', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO book_drafts (id, intake_id, title, slug, author, category, summary, youtube_url, metadata_json, publication_status, created_at, updated_at) VALUES ('youtube-book-04', 'youtube-seed-04', 'ခင်ခင်ထူး - မအိမ်ကံ (စ-ဆုံး ၁)', 'youtube-voz5dl2zkw0', 'ခင်ခင်ထူး', 'အသံစာအုပ်', 'YouTube မှ နားဆင်နိုင်သော အသံဇာတ်လမ်း။', 'https://www.youtube.com/watch?v=voz5DL2ZKW0', '{"source":"seed","sourceType":"youtube","public":{"sourceType":"youtube"}}', 'published', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');

INSERT OR IGNORE INTO intake_items (id, telegram_update_id, telegram_file_id, media_type, source_type, source_url, source_chat_id, source_message_id, status, original_filename, mime_type, created_at, updated_at) VALUES ('youtube-seed-05', -900005, 'youtube:xlIG_Ky77LA', 'document', 'youtube_link', 'https://www.youtube.com/watch?v=xlIG_Ky77LA', 'seed', 5, 'published', 'ပုညခင် - တကယ်ချစ်လို့ရူးခဲ့သည်', 'text/uri-list', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO rights_records (id, intake_id, rights_status, evidence_note, created_at, updated_at) VALUES ('youtube-rights-05', 'youtube-seed-05', 'missing', 'YouTube link seed; verify rights before relying on continued availability.', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO book_drafts (id, intake_id, title, slug, author, category, summary, youtube_url, metadata_json, publication_status, created_at, updated_at) VALUES ('youtube-book-05', 'youtube-seed-05', 'ပုညခင် - တကယ်ချစ်လို့ရူးခဲ့သည်', 'youtube-xlig-ky77la', 'ပုညခင်', 'အသံစာအုပ်', 'YouTube မှ နားဆင်နိုင်သော အသံဇာတ်လမ်း။', 'https://www.youtube.com/watch?v=xlIG_Ky77LA', '{"source":"seed","sourceType":"youtube","public":{"sourceType":"youtube"}}', 'published', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');

INSERT OR IGNORE INTO intake_items (id, telegram_update_id, telegram_file_id, media_type, source_type, source_url, source_chat_id, source_message_id, status, original_filename, mime_type, created_at, updated_at) VALUES ('youtube-seed-06', -900006, 'youtube:8IdeddAhXhU', 'document', 'youtube_link', 'https://www.youtube.com/watch?v=8IdeddAhXhU', 'seed', 6, 'published', 'မြညိုချစ်သောကိုရင်သြ', 'text/uri-list', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO rights_records (id, intake_id, rights_status, evidence_note, created_at, updated_at) VALUES ('youtube-rights-06', 'youtube-seed-06', 'missing', 'YouTube link seed; verify rights before relying on continued availability.', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO book_drafts (id, intake_id, title, slug, author, category, summary, youtube_url, metadata_json, publication_status, created_at, updated_at) VALUES ('youtube-book-06', 'youtube-seed-06', 'မြညိုချစ်သောကိုရင်သြ', 'youtube-8ideddahxhu', 'ဘီအီးဒီအောင်သိုက်', 'အသံစာအုပ်', 'YouTube မှ နားဆင်နိုင်သော အသံဇာတ်လမ်း။', 'https://www.youtube.com/watch?v=8IdeddAhXhU', '{"source":"seed","sourceType":"youtube","public":{"sourceType":"youtube"}}', 'published', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');

INSERT OR IGNORE INTO intake_items (id, telegram_update_id, telegram_file_id, media_type, source_type, source_url, source_chat_id, source_message_id, status, original_filename, mime_type, created_at, updated_at) VALUES ('youtube-seed-07', -900007, 'youtube:vjjrrKY8wNw', 'document', 'youtube_link', 'https://www.youtube.com/watch?v=vjjrrKY8wNw', 'seed', 7, 'published', 'နေထွက်ရာအရပ်ကိုအရှေ့ဟုခေါ်သည်', 'text/uri-list', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO rights_records (id, intake_id, rights_status, evidence_note, created_at, updated_at) VALUES ('youtube-rights-07', 'youtube-seed-07', 'missing', 'YouTube link seed; verify rights before relying on continued availability.', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO book_drafts (id, intake_id, title, slug, author, category, summary, youtube_url, metadata_json, publication_status, created_at, updated_at) VALUES ('youtube-book-07', 'youtube-seed-07', 'နေထွက်ရာအရပ်ကိုအရှေ့ဟုခေါ်သည်', 'youtube-vjjrrky8wnw', 'ဘီအီးဒီအောင်သိုက်', 'အသံစာအုပ်', 'YouTube မှ နားဆင်နိုင်သော အသံဇာတ်လမ်း။', 'https://www.youtube.com/watch?v=vjjrrKY8wNw', '{"source":"seed","sourceType":"youtube","public":{"sourceType":"youtube"}}', 'published', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');

INSERT OR IGNORE INTO intake_items (id, telegram_update_id, telegram_file_id, media_type, source_type, source_url, source_chat_id, source_message_id, status, original_filename, mime_type, created_at, updated_at) VALUES ('youtube-seed-08', -900008, 'youtube:svQxnHDFfG8', 'document', 'youtube_link', 'https://www.youtube.com/watch?v=svQxnHDFfG8', 'seed', 8, 'published', 'မရွှေအထက်တန်းစား', 'text/uri-list', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO rights_records (id, intake_id, rights_status, evidence_note, created_at, updated_at) VALUES ('youtube-rights-08', 'youtube-seed-08', 'missing', 'YouTube link seed; verify rights before relying on continued availability.', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO book_drafts (id, intake_id, title, slug, author, category, summary, youtube_url, metadata_json, publication_status, created_at, updated_at) VALUES ('youtube-book-08', 'youtube-seed-08', 'မရွှေအထက်တန်းစား', 'youtube-svqxnhdffg8', 'ဘီအီးဒီအောင်သိုက် (ထက်နေချမ်း၊ စောယုနန္ဒာ)', 'အသံစာအုပ်', 'YouTube မှ နားဆင်နိုင်သော အသံဇာတ်လမ်း။', 'https://www.youtube.com/watch?v=svQxnHDFfG8', '{"source":"seed","sourceType":"youtube","public":{"sourceType":"youtube"}}', 'published', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');

INSERT OR IGNORE INTO intake_items (id, telegram_update_id, telegram_file_id, media_type, source_type, source_url, source_chat_id, source_message_id, status, original_filename, mime_type, created_at, updated_at) VALUES ('youtube-seed-09', -900009, 'youtube:P_4RjDkwVa8', 'document', 'youtube_link', 'https://www.youtube.com/watch?v=P_4RjDkwVa8', 'seed', 9, 'published', 'ရွှေအသဲ ငွေအသဲ စိန်နဲ့ခွဲ', 'text/uri-list', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO rights_records (id, intake_id, rights_status, evidence_note, created_at, updated_at) VALUES ('youtube-rights-09', 'youtube-seed-09', 'missing', 'YouTube link seed; verify rights before relying on continued availability.', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO book_drafts (id, intake_id, title, slug, author, category, summary, youtube_url, metadata_json, publication_status, created_at, updated_at) VALUES ('youtube-book-09', 'youtube-seed-09', 'ရွှေအသဲ ငွေအသဲ စိန်နဲ့ခွဲ', 'youtube-p-4rjdkwva8', 'ဘီအီးဒီအောင်သိုက် (ဧငြိမ်းဖြူ၊ စောယုနန္ဒာ)', 'အသံစာအုပ်', 'YouTube မှ နားဆင်နိုင်သော အသံဇာတ်လမ်း။', 'https://www.youtube.com/watch?v=P_4RjDkwVa8', '{"source":"seed","sourceType":"youtube","public":{"sourceType":"youtube"}}', 'published', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');

INSERT OR IGNORE INTO intake_items (id, telegram_update_id, telegram_file_id, media_type, source_type, source_url, source_chat_id, source_message_id, status, original_filename, mime_type, created_at, updated_at) VALUES ('youtube-seed-10', -900010, 'youtube:7qzTpnmmSEI', 'document', 'youtube_link', 'https://www.youtube.com/watch?v=7qzTpnmmSEI', 'seed', 10, 'published', 'အရုပ်မျက်နှာရှာတော်ပုံ', 'text/uri-list', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO rights_records (id, intake_id, rights_status, evidence_note, created_at, updated_at) VALUES ('youtube-rights-10', 'youtube-seed-10', 'missing', 'YouTube link seed; verify rights before relying on continued availability.', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO book_drafts (id, intake_id, title, slug, author, category, summary, youtube_url, metadata_json, publication_status, created_at, updated_at) VALUES ('youtube-book-10', 'youtube-seed-10', 'အရုပ်မျက်နှာရှာတော်ပုံ', 'youtube-7qztpnmmsei', 'ဘီအီးဒီအောင်သိုက်', 'အသံစာအုပ်', 'YouTube မှ နားဆင်နိုင်သော အသံဇာတ်လမ်း။', 'https://www.youtube.com/watch?v=7qzTpnmmSEI', '{"source":"seed","sourceType":"youtube","public":{"sourceType":"youtube"}}', 'published', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');

INSERT OR IGNORE INTO intake_items (id, telegram_update_id, telegram_file_id, media_type, source_type, source_url, source_chat_id, source_message_id, status, original_filename, mime_type, created_at, updated_at) VALUES ('youtube-seed-11', -900011, 'youtube:pP7OBXlIMls', 'document', 'youtube_link', 'https://www.youtube.com/watch?v=pP7OBXlIMls', 'seed', 11, 'published', 'ရိုမီယိုလို ဒဿလို', 'text/uri-list', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO rights_records (id, intake_id, rights_status, evidence_note, created_at, updated_at) VALUES ('youtube-rights-11', 'youtube-seed-11', 'missing', 'YouTube link seed; verify rights before relying on continued availability.', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO book_drafts (id, intake_id, title, slug, author, category, summary, youtube_url, metadata_json, publication_status, created_at, updated_at) VALUES ('youtube-book-11', 'youtube-seed-11', 'ရိုမီယိုလို ဒဿလို', 'youtube-pp7obxlimls', 'ဘီအီးဒီအောင်သိုက်', 'အသံစာအုပ်', 'YouTube မှ နားဆင်နိုင်သော အသံဇာတ်လမ်း။', 'https://www.youtube.com/watch?v=pP7OBXlIMls', '{"source":"seed","sourceType":"youtube","public":{"sourceType":"youtube"}}', 'published', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');

INSERT OR IGNORE INTO intake_items (id, telegram_update_id, telegram_file_id, media_type, source_type, source_url, source_chat_id, source_message_id, status, original_filename, mime_type, created_at, updated_at) VALUES ('youtube-seed-12', -900012, 'youtube:H-m_t-ZVASY', 'document', 'youtube_link', 'https://www.youtube.com/watch?v=H-m_t-ZVASY', 'seed', 12, 'published', 'မရွှေအထက်တန်းစား (နောက်တစ်မျိုး)', 'text/uri-list', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO rights_records (id, intake_id, rights_status, evidence_note, created_at, updated_at) VALUES ('youtube-rights-12', 'youtube-seed-12', 'missing', 'YouTube link seed; verify rights before relying on continued availability.', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
INSERT OR IGNORE INTO book_drafts (id, intake_id, title, slug, author, category, summary, youtube_url, metadata_json, publication_status, created_at, updated_at) VALUES ('youtube-book-12', 'youtube-seed-12', 'မရွှေအထက်တန်းစား (နောက်တစ်မျိုး)', 'youtube-h-m-t-zvasy', 'ဘီအီးဒီအောင်သိုက်', 'အသံစာအုပ်', 'YouTube မှ နားဆင်နိုင်သော အသံဇာတ်လမ်း။', 'https://www.youtube.com/watch?v=H-m_t-ZVASY', '{"source":"seed","sourceType":"youtube","public":{"sourceType":"youtube"}}', 'published', '2026-10-10T00:00:00.000Z', '2026-10-10T00:00:00.000Z');
